### PR TITLE
fix: added valid options for provisioners

### PR DESCRIPTION
**Pull request by Al-Pragliola**
This PR aims to add the list of supported provisioners to cluster/bootstrap template cmd

### CODE REVIEW

**Review by omissis — COMMENTED** [review]
While this is a small pr, I find it a bit over-engineered. Adding the list of providers straight in the help text string would do the same without introducing extra complexity, i.e.:
```
"Bootstrap provisioner, valid options are: aws, gcp"
```

**Comment by ralgozino** [comment]
Hi @Al-Pragliola 
I kind of agree with @omissis on this one. If we can't get/detect the supported list in a smarter way and we'll need to maintain the variable in the provisioners.go file, it would be simpler to just have it in the help text.

Also, can we point this PR to `master` instead of `fury-next` please? The `fury-next` branch will be removed.

Thanks!

**Review by ralgozino — CHANGES_REQUESTED** [review]
as per the previous comment

**Review by omissis — APPROVED** [review]
SBAM

**Review by ralgozino — APPROVED** [review]

**Pull request merged**
