### PR TITLE
chore: removing useless Boundary setup from Ansible

### PR DESCRIPTION
**Pull request by lzecca78**
Because boundary became not used at all, is something that we don't need in the ansible setup, so I've removed the task from the Ansible.

### CODE REVIEW

**Comment by omissis** [comment]
@lzecca78 I see boundary is still mentioned in tests and go code, can it be removed there, too?

**Comment by omissis** [comment]
@lzecca78 there is a broken test

**Review by omissis — APPROVED** [review]
once the failing test is fixed, SBAM

**Comment by omissis** [comment]
@lzecca78 I fixed the test, SBAM for me

**Review by ralgozino — APPROVED** [review]
The PR itself LGTM, but let's **not** merge it until we have a clear picture of what else needs to be done to drop boundary/connect.

**Comment by lzecca78** [comment]
Totally agree, I move this to draft in the meanwhile to avoid unwanted merge 👍

**Comment by ralgozino** [comment]
thank you @lzecca78 🙏

**Comment by nutellinoit** [comment]
Is this still relevant with furyctl-ng? @Al-Pragliola , if not, we can close the PR

**Comment by Al-Pragliola** [comment]
> Is this still relevant with furyctl-ng? @Al-Pragliola , if not, we can close the PR

boundary is relevant only to the vSphere provisioner, therefore is not included at the moment in furyctl-ng, reading the comments this PR should may be relevant to this: https://github.com/orgs/sighupio/projects/3/views/1?filterQuery=boundary&pane=issue&itemId=9922474 @ralgozino @omissis

**Pull request merged**
