### PR TITLE
Typo in struct for GKE provider

### PR DESCRIPTION
**Pull request by lzecca78**
hi everyone 👋 ,
working side by side with the repo of furyctl I noticed these typos.

### CODE REVIEW

**Review by ralgozino — COMMENTED** [review]
overall lgtm, a few questions before approving:
1. This doesn't change anything user-side, right?
2. Have you checked if we need to update something in the [installer](https://github.com/sighupio/fury-gke-installer)?

Thank you!

**Review by luigibarbato — APPROVED** [review]
SBAM

**Review by ralgozino — APPROVED** [review]
lgtm

**Review by omissis — APPROVED** [review]
SBAM

**Review by Al-Pragliola — APPROVED** [review]
SBAM

**Pull request merged**
