### PR TITLE
fix: provisioner flag is case sensitive

### PR DESCRIPTION
**Pull request by luigibarbato**
Currently, the provisioner flag is case sentive. This PR aims to solve this problem, lowerizing the provisioner flag value.

### CODE REVIEW

**Comment by ralgozino** [comment]
Hi @luigibarbato , I think that you meant that the flag IS case sensitive, right? 
(and `currently` instead of `actually`)

can we point this PR to `master` instead of `fury-next` please? The `fury-next` branch will be removed.

Thanks!

**Review by ralgozino — CHANGES_REQUESTED** [review]
as per the previous comment

**Comment by luigibarbato** [comment]
> Hi @luigibarbato , I think that you meant that the flag IS case sensitive, right? (and `currently` instead of `actually`)
> 
> can we point this PR to `master` instead of `fury-next` please? The `fury-next` branch will be removed.
> 
> Thanks!

Oh! You're right! I fixed it :)

One question on PR's pointer: Currently, the PR codebase is based on furyctl-next code and the PR branch is aligned with the furyctl-next branch. We would wait for furyctl-next merge so the PR automatically points to master or we would rebase the actual branch with the master branch?

**Comment by ralgozino** [comment]
> One question on PR's pointer: Currently, the PR codebase is based on furyctl-next code and the PR branch is aligned with the furyctl-next branch. We would wait for furyctl-next merge so the PR automatically points to master or we would rebase the actual branch with the master branch?

Hi Luigi, we should rebase and make the PR to `master`, the content in `furyctl-next` is no longer valid and we'll delete it.

**Comment by omissis** [comment]
closed in favor of #85

**Pull request closed without merging**
