### PR TITLE
fix depth subpath bug

### PR DESCRIPTION
**Pull request by lzecca78**
Due to a bug discovered during the provisioning of module velero with @simonemex  and @lnovara   that has. a subdir of multiple path, here it is the patch for this bug. Now the function will handle whatever hierarchy level of subdir will exist in the repo

### CODE REVIEW

**Comment by lzecca78** [comment]
hi @ralgozino , you are right, is my vim configuration that is set in that way. Is pretty the usual configuration, but if is something that have to adapted to a standard, just let me know and i will change it  👍

**Comment by angelbarrera92** [comment]
> Thanks @lzecca78 ! I'm seeing a lot of format changes in the diff (changed from 2 to 4 spaces identation), I think w

I was working on it but there is not ready yet. So feel free to continue the PR

**Comment by lzecca78** [comment]
Anyway I made a search and the standard in yaml Is 2 spaces so I changed my vim setup to match this standard.

**Comment by angelbarrera92** [comment]
LGTM! Waiting for one more feedback, @ralgozino  or @phisco

**Pull request merged**
